apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aws-glue-libs
  description: AWS Glue Libraries are additions and enhancements to Spark for ETL operations.
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
